### ISSUE TITLE
yum clean headers change breaks dnf compatibility

### ISSUE THREAD

**Issue by joemiller** [chef-cookbooks/yum#135]
This change https://github.com/chef-cookbooks/yum/commit/121da3b48754cb082195fe114e897d9e1dcb7d3c which introduced a `yum clean headers` call in place of `yum clean all` has broken compatibility with dnf. We had been using this cook with dnf on fedora-22 for several weeks with no other issues, FWIW.

```
    docker: [2015-09-08T01:20:15+00:00] ERROR: yum_repository[fedora] (pantheon_package_repository::fedora line 8) had an error: Mixlib::ShellOut::ShellCommandFailed: execute[yum clean fedora] (/opt/pantheon/infrastructure/cookbooks/yum/providers/repository.rb line 55) had an error: Mixlib::ShellOut::ShellCommandFailed: Expected process to exit with [0], but received '1'
    docker: ---- Begin output of yum clean headers --disablerepo=* --enablerepo=fedora ----
    docker: STDOUT:
    docker: STDERR: Yum command has been deprecated, redirecting to '/usr/bin/dnf clean headers --disablerepo=* --enablerepo=fedora'.
    docker: See 'man dnf' and 'man yum2dnf' for more information.
    docker: To transfer transaction metadata from yum to DNF, run:
    docker: 'dnf install python-dnf-plugins-extras-migrate && dnf-2 migrate'
    docker:
    docker: Error: invalid clean argument: u'headers'
    docker: Mini usage:
    docker:
    docker: clean [packages|metadata|dbcache|plugins|expire-cache|all]
```

`yum clean metadata` might be an acceptable compromise for yum and dnf? I'm not sure what the difference between metadata and headers is, though, and mostly just wondering if someone else already has a good answer here.
